### ISSUE TITLE
Development status and GitHub release

### ISSUE THREAD

**Issue by baimafeima** [nlaplante/envelope#2]
What is the current development status of this project? Have you found a new maintainer? In any case, could you make a release here on GitHub (versioned tarballs)? What similar maintained projects can you recommend? Thank you.

**Comment by nlaplante** [comment]
The code hosted here is for backup purposes only. I don't work on this project anymore. I put it here due to people requesting access to the code to fork it. Nobody volunteered to maintain this project as of yet. 

The code is not release-ready so that's why there are no releases. [See the list of forks](https://github.com/nlaplante/envelope/network) to track further development.

Closing this. Good luck!

**Comment by baimafeima** [comment]
Thank you for the updates.
